name: Build and run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Boost
      run: sudo apt install -y libboost-graph1.65-dev

    - name: Configure
      run: ./configure --build-type=Release

    - name: Build
      run: make -C build -j2

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure
