name: Build and run tests

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC",
            artifact: "Linux.tar.xz",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "gcc",
            cxx: "g++"
          }
        - {
            name: "macOS Latest Clang",
            artifact: "macOS.tar.xz",
            os: macos-latest,
            build_type: "Release",
            cc: "clang",
            cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v1

    - name: Install Boost
      run: |
        if [ "$(uname)" == "Darwin" ]; then
          brew install boost
        elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
          sudo apt install -y libboost-graph-dev
        fi

    - name: Configure
      run: ./configure --build-type=Release

    - name: Build
      run: make -C build -j2

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure
